<?php require_once dirname(__FILE__).'/item-list.phtml' ?>
<?php require_once dirname(__FILE__).'/item-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/item-propgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/item-propform.phtml' ?>



<?php
$customrecordstatus = __DIR__.'/item-customrecordstatus.phtml'; 
if (is_file($customrecordstatus)) {
	include $customrecordstatus;
} else { ?>

<?php } ?>
