<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_edit-caption">{{STATE_BEG}}Budget Group{{STATE_END}}</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_cobgroup_id" class="easyui-textbox" mapping="cobgroup_id" uppercase="true" maxlength="17" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'ID harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Group Budget</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_cobgroup_name" class="easyui-textbox" mapping="cobgroup_name" uppercase="true" maxlength="90" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Nama Group COA harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_cobgroup_descr" class="easyui-textbox" mapping="cobgroup_descr"  maxlength="255" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_cobgroup_isparent" class="easyui-checkbox c1" mapping="cobgroup_isparent" data-options="label: 'Group Is Parent', labelPosition: 'after', checked: false , labelWidth: '200px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_cobgroup_isdisabled" class="easyui-checkbox c1" mapping="cobgroup_isdisabled" data-options="label: 'Disabled', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Parent</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_cobgroup_parent" class="easyui-combo" style="width: 400px" mapping="cobgroup_parent" display="cobgroup_parent_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: '-- PILIH --'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Path</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_cobgroup_path" class="easyui-textbox" mapping="cobgroup_path" uppercase="true" maxlength="340" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">PathId</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_cobgroup_pathid" class="easyui-textbox" mapping="cobgroup_pathid" uppercase="true" maxlength="17" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Level</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_cobgroup_level" class="easyui-numberbox" mapping="cobgroup_level" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width">Simpan</a>
		</div>
	</div>	





	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol-tombol xtion disini -->
			<?php
			$customheaderxtion = __DIR__.'/cobgroup-edit-customxtion.phtml'; 
			if (is_file($customheaderxtion)) {
				include $customheaderxtion;
			} else { ?>
			
			
			
			
			<?php } ?>
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5 fgta-button-delete" style="margin-bottom: 10px; margin-right: 10px">Hapus</a>
		</div>
	</div>

</div>

