<div id="pnl_editspecform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_editspecform-caption">{{STATE_BEG}}Spesifikasi{{STATE_END}}</div>
		<a id="pnl_editspecform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editspecform-title" class="fgta-page-subtitle">XXXXXXX</div>


	<form id="pnl_editspecform-form">

		<div class="form_row pnl_editspecform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editspecform-txt_itemassetspec_id" class="easyui-textbox" mapping="itemassetspec_id" uppercase="true" maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editspecform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Value</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editspecform-txt_itemassetspec_value" class="easyui-textbox" mapping="itemassetspec_value"  maxlength="90"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editspecform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Spec</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editspecform-cbo_itemspec_id" class="easyui-combo" style="width: 400px" mapping="itemspec_id" display="itemspec_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Item Spesifikasi harus diisi'"  validType="requiredcombo['pnl_editspecform-cbo_itemspec_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editspecform_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editspecform-chk_itemspec_isnumber" class="easyui-checkbox c1" mapping="itemspec_isnumber" data-options="label: 'Number', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_editspecform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Item</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editspecform-txt_itemasset_id" class="easyui-textbox" mapping="itemasset_id" uppercase="true" maxlength="14"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editspecform-autoadd" type="checkbox"><label for="pnl_editspecform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editspecform-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	


	<?php
	$custombuttonbar = __DIR__.'/itemasset-specform-custombuttonbar.phtml';
	if (is_file($custombuttonbar)) {
		include $custombuttonbar;
	} else { ?>
	<div id="pnl_editspecform-buttonbar" style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div id="pnl_editspecform-buttonbar-left">
			<a id="pnl_editspecform-btn_prev" class="easyui-linkbutton c8 fgta-button-detilprev" style="width: 50px">Prev</a>
			<a id="pnl_editspecform-btn_next" class="easyui-linkbutton c8 fgta-button-detilnext" style="width: 50px">Next</a>
		</div>

		<div id="pnl_editspecform-buttonbar-middle">
			<a id="pnl_editspecform-btn_addnew" class="easyui-linkbutton c8 fgta-button-detiladd" style="width: 100px">Tambah Baru</a>
		</div>

		<div id="pnl_editspecform-buttonbar-right">
			<a id="pnl_editspecform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>
	<?php } ?>




</div>	
