<?php require_once dirname(__FILE__).'/itemasset-list.phtml' ?>
<?php require_once dirname(__FILE__).'/itemasset-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/itemasset-propgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/itemasset-propform.phtml' ?>
<?php require_once dirname(__FILE__).'/itemasset-depregrid.phtml' ?>
<?php require_once dirname(__FILE__).'/itemasset-depreform.phtml' ?>



<?php
$customrecordstatus = __DIR__.'/itemasset-customrecordstatus.phtml'; 
if (is_file($customrecordstatus)) {
	include $customrecordstatus;
} else { ?>

<?php } ?>
