<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Week</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_week_id" class="easyui-textbox" mapping="week_id"  maxlength="7" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Year</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_week_year" class="easyui-numberbox" mapping="week_year" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Month</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_week_month" class="easyui-numberbox" mapping="week_month" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Number</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_week_number" class="easyui-numberbox" mapping="week_number" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Interval</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_week_interval" class="easyui-numberbox" mapping="week_interval" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Start</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-dt_week_dtstart" class="easyui-datebox" style="width: 400px" mapping="week_dtstart" data-options="editable:false ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">End</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-dt_week_dtend" class="easyui-datebox" style="width: 400px" mapping="week_dtend" data-options="editable:false ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	



		<div id="pnl_edit-detil" class="form_row" style="margin-top: 30px">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<div class="fgtable-head" style="height: 25px; padding: 5px 0px 0px 5px">Detil Informations</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 0px 0px 5px" onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editdategrid')">Date</div>

			</div>		
		</div>		
		
		


	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="width">Hapus</a>
		</div>
	</div>

</div>

