<thead>
	<tr>
		<th mapping="unit_id">unit_id</th>
		<th mapping="unit_name">unit_name</th>
		<th mapping="unit_isdisabled" type="checkbox">unit_isdisabled</th>

	</tr>
	<tr style="background-color: #cccccc; height: 30px">
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
		<td class="fgtable-head" style="border-bottom: 1px solid #000000">Unit</td>
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Disabled</td>

	</tr>
</thead>