<?php require_once dirname(__FILE__).'/site-list.phtml' ?>
<?php require_once dirname(__FILE__).'/site-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/site-unitgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/site-unitform.phtml' ?>
<?php require_once dirname(__FILE__).'/site-mappinggrid.phtml' ?>
<?php require_once dirname(__FILE__).'/site-mappingform.phtml' ?>
<?php require_once dirname(__FILE__).'/site-eventgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/site-eventform.phtml' ?>

