<div id="pnl_editunitform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Unit</div>
		<a id="pnl_editunitform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editunitform-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<form id="pnl_editunitform-form">

		<div class="form_row">
			<div class="form_label_col">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editunitform-txt_siteunit_id" class="easyui-textbox" mapping="siteunit_id" uppercase="true" maxlength="14"  style="width: 400px" data-options="multiline:false  ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Unit</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editunitform-cbo_unit_id" class="easyui-combo" style="width: 400px" mapping="unit_id" display="unit_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Unit harus diisi', prompt: '-- PILIH --'">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Dept</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editunitform-cbo_dept_id" class="easyui-combo" style="width: 400px" mapping="dept_id" display="dept_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Departemen harus diisi', prompt: '-- PILIH --'">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Site</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editunitform-txt_site_id" class="easyui-textbox" mapping="site_id" uppercase="true" maxlength="30"  style="width: 400px" data-options="multiline:false  , disabled: true">
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editunitform-autoadd" type="checkbox"><label for="pnl_editunitform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editunitform-btn_save" class="easyui-linkbutton c1" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	



	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<a id="pnl_editunitform-btn_prev" class="easyui-linkbutton c8" style="width: 50px">Prev</a>
			<a id="pnl_editunitform-btn_next" class="easyui-linkbutton c8" style="width: 50px">Next</a>
		</div>

		<div>
			<a id="pnl_editunitform-btn_addnew" class="easyui-linkbutton c8" style="width: 100px">Tambah Baru</a>
		</div>

		<div>
			<a id="pnl_editunitform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>




</div>	
