<div id="pnl_editeventform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Event</div>
		<a id="pnl_editeventform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editeventform-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<form id="pnl_editeventform-form">

		<div class="form_row">
			<div class="form_label_col">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editeventform-txt_siteevent_id" class="easyui-textbox" mapping="siteevent_id" uppercase="true" maxlength="14"  style="width: 400px" data-options="multiline:false  ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Event Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editeventform-txt_siteevent_name" class="easyui-textbox" mapping="siteevent_name" uppercase="true" maxlength="60"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'Event Name harus diisi' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editeventform-dt_siteevent_date" class="easyui-datebox" style="width: 400px" mapping="siteevent_date" data-options="editable:false ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editeventform-chk_siteevent_enabling" class="easyui-checkbox c1" mapping="siteevent_enabling" data-options="label: 'Enabling', labelPosition: 'after', disabled:false, checked: false ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editeventform-chk_siteevent_disabling" class="easyui-checkbox c1" mapping="siteevent_disabling" data-options="label: 'Disabling', labelPosition: 'after', disabled:false, checked: false ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Site</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editeventform-txt_site_id" class="easyui-textbox" mapping="site_id" uppercase="true" maxlength="30"  style="width: 400px" data-options="multiline:false  , disabled: true">
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editeventform-autoadd" type="checkbox"><label for="pnl_editeventform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editeventform-btn_save" class="easyui-linkbutton c1" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	



	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<a id="pnl_editeventform-btn_prev" class="easyui-linkbutton c8" style="width: 50px">Prev</a>
			<a id="pnl_editeventform-btn_next" class="easyui-linkbutton c8" style="width: 50px">Next</a>
		</div>

		<div>
			<a id="pnl_editeventform-btn_addnew" class="easyui-linkbutton c8" style="width: 100px">Tambah Baru</a>
		</div>

		<div>
			<a id="pnl_editeventform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>




</div>	
