<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_edit-caption">{{STATE_BEG}}Marital{{STATE_END}}</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_marital_id" class="easyui-textbox" mapping="marital_id" uppercase="true" maxlength="2" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'ID harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Marital Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_marital_name" class="easyui-textbox" mapping="marital_name" uppercase="true" maxlength="30" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Marital name harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_marital_descr" class="easyui-textbox" mapping="marital_descr"  maxlength="90" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Ptkp Tambahan</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_marital_ptkpval" class="easyui-numberbox" mapping="marital_ptkpval" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width">Simpan</a>
		</div>
	</div>	





	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol-tombol xtion disini -->
			<?php
			$customheaderxtion = __DIR__.'/marital-edit-customxtion.phtml'; 
			if (is_file($customheaderxtion)) {
				include $customheaderxtion;
			} else { ?>
			
			
			
			
			<?php } ?>
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5 fgta-button-delete" style="margin-bottom: 10px; margin-right: 10px">Hapus</a>
		</div>
	</div>

</div>

