<?php require_once dirname(__FILE__).'/site-list.phtml' ?>
<?php require_once dirname(__FILE__).'/site-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/site-unitgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/site-unitform.phtml' ?>
<?php require_once dirname(__FILE__).'/site-eventgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/site-eventform.phtml' ?>
<?php require_once dirname(__FILE__).'/site-refgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/site-refform.phtml' ?>



<?php
$customrecordstatus = __DIR__.'/site-customrecordstatus.phtml'; 
if (is_file($customrecordstatus)) {
	include $customrecordstatus;
} else { ?>

<?php } ?>
