<div id="pnl_editcontactform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_editcontactform-caption">{{STATE_BEG}}Contact{{STATE_END}}</div>
		<a id="pnl_editcontactform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editcontactform-title" class="fgta-page-subtitle">XXXXXXX</div>


	<form id="pnl_editcontactform-form">

		<div class="form_row pnl_editcontactform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcontactform-txt_partnercontact_id" class="easyui-textbox" mapping="partnercontact_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editcontactform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcontactform-txt_partnercontact_name" class="easyui-textbox" mapping="partnercontact_name" uppercase="true" maxlength="100"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'Name harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editcontactform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Position</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcontactform-txt_partnercontact_position" class="easyui-textbox" mapping="partnercontact_position" uppercase="true" maxlength="30"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'Position harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editcontactform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">HP</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcontactform-txt_partnercontact_mobilephone" class="easyui-textbox" mapping="partnercontact_mobilephone" uppercase="true" maxlength="30"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'HP harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editcontactform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Email</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcontactform-txt_partnercontact_email" class="easyui-textbox" mapping="partnercontact_email" lowercase="true" maxlength="150"  style="width: 400px" data-options="multiline:false , required: true, validType: ['email'], invalidMessage: 'Email harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editcontactform_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcontactform-chk_partnecontact_isdisabled" class="easyui-checkbox c1" mapping="partnecontact_isdisabled" data-options="label: 'Disabled', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_editcontactform_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcontactform-chk_partnecontact_iscontract" class="easyui-checkbox c1" mapping="partnecontact_iscontract" data-options="label: 'PIC - Contract', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_editcontactform_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcontactform-chk_partnecontact_isinvoice" class="easyui-checkbox c1" mapping="partnecontact_isinvoice" data-options="label: 'PIC - Invoice', labelPosition: 'after', checked: false , labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_editcontactform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Partner</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editcontactform-txt_partner_id" class="easyui-textbox" mapping="partner_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editcontactform-autoadd" type="checkbox"><label for="pnl_editcontactform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editcontactform-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	


	<?php
	$custombuttonbar = __DIR__.'/partner-contactform-custombuttonbar.phtml';
	if (is_file($custombuttonbar)) {
		include $custombuttonbar;
	} else { ?>
	<div id="pnl_editcontactform-buttonbar" style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div id="pnl_editcontactform-buttonbar-left">
			<a id="pnl_editcontactform-btn_prev" class="easyui-linkbutton c8 fgta-button-detilprev" style="width: 50px">Prev</a>
			<a id="pnl_editcontactform-btn_next" class="easyui-linkbutton c8 fgta-button-detilnext" style="width: 50px">Next</a>
		</div>

		<div id="pnl_editcontactform-buttonbar-middle">
			<a id="pnl_editcontactform-btn_addnew" class="easyui-linkbutton c8 fgta-button-detiladd" style="width: 100px">Tambah Baru</a>
		</div>

		<div id="pnl_editcontactform-buttonbar-right">
			<a id="pnl_editcontactform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>
	<?php } ?>




</div>	
