<div id="pnl_editcontactgrid">
	<div class="fgta-page-title">Daftar Contact</div>
	<div id="pnl_editcontactgrid-title" class="fgta-page-subtitle">XXXXXXX</div>

	<!--// Untuk keperluan search di detil
	<div id="pnl_editcontactgrid-pnl_head" style="display: flex; align-items: flex-end">
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_editcontactgrid-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_editcontactgrid-btn_load" class="easyui-linkbutton c8 fgta-button-listload" style="width: 45px">Load</a>
			</div>
		</div>
	</div>	
	//-->


	<?php
	$customheadpanel = __DIR__.'/partner-contactgrid-customheadpanel.phtml';
	if (is_file($customheadpanel)) {
		include $customheadpanel;
	} 
	?>

	<div style="margin-top: 10px; margin-bottom: 15px">
		<table id="pnl_editcontactgrid-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<?php
			$customview = __DIR__.'/partner-contactgrid-customview.phtml'; 
			if (is_file($customview)) {
				include $customview;
			} else { ?>
			<thead>

				<tr>
<th type="check">chk</th>					
					<th mapping="partnercontact_id">partnercontact_id</th>
					<th mapping="partnercontact_name">partnercontact_name</th>
					<th mapping="partnercontact_position">partnercontact_position</th>
					<th mapping="partnercontact_mobilephone">partnercontact_mobilephone</th>
					<th mapping="partnercontact_email">partnercontact_email</th>
					<th mapping="partnecontact_isdisabled" type="checkbox">partnecontact_isdisabled</th>
					<th mapping="partnecontact_iscontract" type="checkbox">partnecontact_iscontract</th>
					<th mapping="partnecontact_isinvoice" type="checkbox">partnecontact_isinvoice</th>

					<th mapping=""></th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
<td class="fgtable-head rowcheck" style="width: 30px; border-bottom: 1px solid #000000; text-align: center">*</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Name</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Position</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">HP</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Email</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Disabled</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">PIC - Contract</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">PIC - Invoice</td>

					<td class="fgtable-head" style="border-bottom: 1px solid #000000; text-align: center">&nbsp;</td>
				</tr>
			</thead>
			<?php } ?>
			
			<?php
			$tablefooter = __DIR__.'/partner-contactgrid-tablefooter.phtml';
			if (is_file($tablefooter)) {
				include $tablefooter;
			} 
			?>
			
		</table>
	</div>



	<div class="pnl_editcontactgrid-control" style="display: flex; justify-content: space-between; margin-bottom: 100px">
		<div>
			<a id="pnl_editcontactgrid-removechecked" href="javascript:void(0)" class="easyui-linkbutton c8 fgta-button-rowdel">Hapus Checked</a>
		</div>

		<div>
			<a id="pnl_editcontactgrid-addrow" href="javascript:void(0)" class="easyui-linkbutton c8 fgta-button-rowadd">Tambah Baris</a>
		</div>

		<div>
		</div>

	</div>



	<?php
	$customfootpanel = __DIR__.'/partner-contactgrid-customfootpanel.phtml';
	if (is_file($customfootpanel)) {
		include $customfootpanel;
	} 
	?>

</div>	
