<div id="pnl_editbankform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_editbankform-caption">{{STATE_BEG}}Bank{{STATE_END}}</div>
		<a id="pnl_editbankform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editbankform-title" class="fgta-page-subtitle">XXXXXXX</div>


	<form id="pnl_editbankform-form">

		<div class="form_row pnl_editbankform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editbankform-txt_partnerbank_id" class="easyui-textbox" mapping="partnerbank_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editbankform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Account Number</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editbankform-txt_partnerbank_accnum" class="easyui-textbox" mapping="partnerbank_accnum" uppercase="true" maxlength="30"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editbankform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Account Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editbankform-txt_partnerbank_accname" class="easyui-textbox" mapping="partnerbank_accname" uppercase="true" maxlength="90"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editbankform_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editbankform-chk_partnerbank_isdisabled" class="easyui-checkbox c1" mapping="partnerbank_isdisabled" data-options="label: 'Disabled', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_editbankform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Bank</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editbankform-cbo_bank_id" class="easyui-combo" style="width: 400px" mapping="bank_id" display="bank_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Bank harus diisi'"  validType="requiredcombo['pnl_editbankform-cbo_bank_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editbankform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Partner</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editbankform-txt_partner_id" class="easyui-textbox" mapping="partner_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editbankform-autoadd" type="checkbox"><label for="pnl_editbankform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editbankform-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	


	<?php
	$custombuttonbar = __DIR__.'/partner-bankform-custombuttonbar.phtml';
	if (is_file($custombuttonbar)) {
		include $custombuttonbar;
	} else { ?>
	<div id="pnl_editbankform-buttonbar" style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div id="pnl_editbankform-buttonbar-left">
			<a id="pnl_editbankform-btn_prev" class="easyui-linkbutton c8 fgta-button-detilprev" style="width: 50px">Prev</a>
			<a id="pnl_editbankform-btn_next" class="easyui-linkbutton c8 fgta-button-detilnext" style="width: 50px">Next</a>
		</div>

		<div id="pnl_editbankform-buttonbar-middle">
			<a id="pnl_editbankform-btn_addnew" class="easyui-linkbutton c8 fgta-button-detiladd" style="width: 100px">Tambah Baru</a>
		</div>

		<div id="pnl_editbankform-buttonbar-right">
			<a id="pnl_editbankform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>
	<?php } ?>




</div>	
