<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_edit-caption">{{STATE_BEG}}Partner{{STATE_END}}</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partner_id" class="easyui-textbox" mapping="partner_id"  maxlength="14" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Type</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_partnertype_id" class="easyui-combo" style="width: 400px" mapping="partnertype_id" display="partnertype_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Type harus diisi'"   validType="requiredcombo['pnl_edit-cbo_partnertype_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row employee" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_partnertype_isempl" class="easyui-checkbox c1" mapping="partnertype_isempl" data-options="label: 'Link To Employee', labelPosition: 'after', checked: false , disabled: true, labelWidth: '300px'">
			</div>
		</div>

		<div class="form_row pnl_edit_row employee" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Employee Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_empl_id" class="easyui-combo" style="width: 400px" mapping="empl_id" display="empl_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div id="pnl_edit-partner_name" class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partner_name" class="easyui-textbox" mapping="partner_name" uppercase="true" maxlength="60" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Name harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div id="pnl_edit-partner_addressline1" class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Address</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partner_addressline1" class="easyui-textbox" mapping="partner_addressline1"  maxlength="100" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Alamat harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div id="pnl_edit-partner_addressline2" class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">&nbsp;</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partner_addressline2" class="easyui-textbox" mapping="partner_addressline2"  maxlength="100" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div id="pnl_edit-partner_addressline3" class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">&nbsp;</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partner_addressline3" class="easyui-textbox" mapping="partner_addressline3"  maxlength="100" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">City</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partner_city" class="easyui-textbox" mapping="partner_city" uppercase="true" maxlength="30" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'City harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Post Code</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partner_postcode" class="easyui-textbox" mapping="partner_postcode"  maxlength="10" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Country</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_partner_country" class="easyui-combo" style="width: 400px" mapping="partner_country" display="country_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Country harus diisi'"   validType="requiredcombo['pnl_edit-cbo_partner_country']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Phone</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partner_phone" class="easyui-textbox" mapping="partner_phone"  maxlength="30" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Phone harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">HP</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partner_mobilephone" class="easyui-textbox" mapping="partner_mobilephone"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Email</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partner_email" class="easyui-textbox" mapping="partner_email" lowercase="true" maxlength="150" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">NPWP</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_partner_npwp" class="easyui-textbox" mapping="partner_npwp"  maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_partner_isnonnpwp" class="easyui-checkbox c1" mapping="partner_isnonnpwp" data-options="label: 'Non NPWP', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_partner_isgroup" class="easyui-checkbox c1" mapping="partner_isgroup" data-options="label: 'Group Partner', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_partner_isdisabled" class="easyui-checkbox c1" mapping="partner_isdisabled" data-options="label: 'Disabled', labelPosition: 'after', checked: false ">
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width">Simpan</a>
		</div>
	</div>	



		<div id="pnl_edit-detil" class="form_row" style="margin-top: 30px">
			<div class="form_label_col"></div>
			<div class="form_input_col detilbox" style="border: 0px solid black">
				<div class="fgtable-head" style="height: 25px; padding: 5px 0px 0px 5px">Detil Informations</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_edittypegrid')">
					<div id="pnl_edit-txt_type_title" class="detilgrid-text">Type</div>
					<div id="pnl_edit-txt_type_value" class="detilgrid-value type_totalvalue">&nbsp;</div>
				</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editbankgrid')">
					<div id="pnl_edit-txt_bank_title" class="detilgrid-text">Bank</div>
					<div id="pnl_edit-txt_bank_value" class="detilgrid-value bank_totalvalue">&nbsp;</div>
				</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editcontactgrid')">
					<div id="pnl_edit-txt_contact_title" class="detilgrid-text">Contact</div>
					<div id="pnl_edit-txt_contact_value" class="detilgrid-value contact_totalvalue">&nbsp;</div>
				</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editrefgrid')">
					<div id="pnl_edit-txt_ref_title" class="detilgrid-text">Referensi</div>
					<div id="pnl_edit-txt_ref_value" class="detilgrid-value ref_totalvalue">&nbsp;</div>
				</div>

			</div>		
		</div>		
		
		


	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol-tombol xtion disini -->
			<?php
			$customheaderxtion = __DIR__.'/partner-edit-customxtion.phtml'; 
			if (is_file($customheaderxtion)) {
				include $customheaderxtion;
			} else { ?>
			
			
			
			
			<?php } ?>
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5 fgta-button-delete" style="margin-bottom: 10px; margin-right: 10px">Hapus</a>
		</div>
	</div>

</div>

