<thead>
	<tr>
		<th mapping="partner_id">partner_id</th>
		<th mapping="partner_name">partner_name</th>
		<th mapping="partner_isdisabled" type="checkbox">partner_isdisabled</th>
	</tr>
	<tr style="background-color: #cccccc; height: 30px">
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
		<td class="fgtable-head" style="border-bottom: 1px solid #000000">Name</td>
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Disabled</td>
	</tr>
</thead>