<thead>
	<tr>
		<th mapping="brand_id">brand_id</th>
		<th mapping="brand_name">brand_name</th>
		<th mapping="brand_isdisabled" type="checkbox">brand_isdisabled</th>
	</tr>
	<tr style="background-color: #cccccc; height: 30px">
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
		<td class="fgtable-head" style="border-bottom: 1px solid #000000">Brand</td>
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Disabled</td>
	</tr>
</thead>