<?php require_once dirname(__FILE__).'/docs-list.phtml' ?>
<?php require_once dirname(__FILE__).'/docs-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/docs-authgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/docs-authform.phtml' ?>



<?php
$customrecordstatus = __DIR__.'/docs-customrecordstatus.phtml'; 
if (is_file($customrecordstatus)) {
	include $customrecordstatus;
} else { ?>

<?php } ?>
