<thead>
	<tr>
		<th mapping="dept_name">dept_name</th>
		<th mapping="deptgroup_name">deptgroup_name</th>
		<th mapping="dept_isdisabled" type="checkbox">deptmodel_isdisabled</th>
	</tr>
	<tr style="background-color: #cccccc; height: 30px">
		<td class="fgtable-head" style="border-bottom: 1px solid #000000">Dept Name</td>
		<td class="fgtable-head" style="width: 200px; border-bottom: 1px solid #000000">Group</td>
		<td class="fgtable-head" style="width: 30px; border-bottom: 1px solid #000000; text-align: center">Dis</td>
	</tr>
</thead>