<thead>
	<tr>
		<th mapping="dept_id">dept_id</th>
		<th mapping="dept_name">dept_name</th>
		<th mapping="dept_isdisabled" type="checkbox">deptmodel_isdisabled</th>
	</tr>
	<tr style="background-color: #cccccc; height: 30px">
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
		<td class="fgtable-head" style="border-bottom: 1px solid #000000">Dept Name</td>
		<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Disabled</td>
	</tr>
</thead>