<div id="pnl_editlinkreqgrid">
	<div class="fgta-page-title">Daftar Link Request</div>
	<div id="pnl_editlinkreqgrid-title" class="fgta-page-subtitle">XXXXXXX</div>

	<!--// Untuk keperluan search di detil
	<div id="pnl_editlinkreqgrid-pnl_head" style="display: flex; align-items: flex-end">
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_editlinkreqgrid-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_editlinkreqgrid-btn_load" class="easyui-linkbutton c8 fgta-button-listload" style="width: 45px">Load</a>
			</div>
		</div>
	</div>	
	//-->


	<?php
	$customheadpanel = __DIR__.'/cust-linkreqgrid-customheadpanel.phtml';
	if (is_file($customheadpanel)) {
		include $customheadpanel;
	} 
	?>

	<div style="margin-top: 10px; margin-bottom: 15px">
		<table id="pnl_editlinkreqgrid-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<?php
			$customview = __DIR__.'/cust-linkreqgrid-customview.phtml'; 
			if (is_file($customview)) {
				include $customview;
			} else { ?>
			<thead>

				<tr>
<th type="check">chk</th>					
					<th mapping="custwalinkreq_id">custwalinkreq_id</th>
					<th mapping="ref">ref</th>
					<th mapping="intent">intent</th>
					<th mapping="room_id">room_id</th>
					<th mapping="message">message</th>
					<th mapping="voubatch_id">voubatch_id</th>
					<th mapping="vou_id">vou_id</th>
					<th mapping="crmevent_id">crmevent_id</th>
					<th mapping="code">code</th>
					<th mapping="slpart">slpart</th>
					<th mapping="data">data</th>
					<th mapping="result">result</th>
					<th mapping="status">status</th>
					<th mapping="custwa_id">custwa_id</th>

					<th mapping=""></th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
<td class="fgtable-head rowcheck" style="width: 30px; border-bottom: 1px solid #000000; text-align: center">*</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Ref</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Intent</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Room</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Message</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">VouBatch</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Voucher</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Event</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Code</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">SL part</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Data</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Result</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Status</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Customer</td>

					<td class="fgtable-head" style="border-bottom: 1px solid #000000; text-align: center">&nbsp;</td>
				</tr>
			</thead>
			<?php } ?>
			
			<?php
			$tablefooter = __DIR__.'/cust-linkreqgrid-tablefooter.phtml';
			if (is_file($tablefooter)) {
				include $tablefooter;
			} 
			?>
			
		</table>
	</div>



	<div class="pnl_editlinkreqgrid-control" style="display: flex; justify-content: space-between; margin-bottom: 100px">
		<div>
			<a id="pnl_editlinkreqgrid-removechecked" href="javascript:void(0)" class="easyui-linkbutton c8 fgta-button-rowdel">Hapus Checked</a>
		</div>

		<div>
			<a id="pnl_editlinkreqgrid-addrow" href="javascript:void(0)" class="easyui-linkbutton c8 fgta-button-rowadd">Tambah Baris</a>
		</div>

		<div>
		</div>

	</div>



	<?php
	$customfootpanel = __DIR__.'/cust-linkreqgrid-customfootpanel.phtml';
	if (is_file($customfootpanel)) {
		include $customfootpanel;
	} 
	?>

</div>	
