<div id="pnl_editlinkreqform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_editlinkreqform-caption">{{STATE_BEG}}Link Request{{STATE_END}}</div>
		<a id="pnl_editlinkreqform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editlinkreqform-title" class="fgta-page-subtitle">XXXXXXX</div>


	<form id="pnl_editlinkreqform-form">

		<div class="form_row pnl_editlinkreqform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editlinkreqform-txt_custwalinkreq_id" class="easyui-textbox" mapping="custwalinkreq_id"  maxlength="32"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editlinkreqform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Ref</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editlinkreqform-txt_ref" class="easyui-textbox" mapping="ref"  maxlength="32"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editlinkreqform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Intent</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editlinkreqform-txt_intent" class="easyui-textbox" mapping="intent"  maxlength="128"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editlinkreqform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Room</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editlinkreqform-txt_room_id" class="easyui-textbox" mapping="room_id"  maxlength="32"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editlinkreqform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Message</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editlinkreqform-txt_message" class="easyui-textbox" mapping="message"  maxlength="1024"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editlinkreqform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">VouBatch</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editlinkreqform-txt_voubatch_id" class="easyui-textbox" mapping="voubatch_id"  maxlength="32"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editlinkreqform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Voucher</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editlinkreqform-txt_vou_id" class="easyui-textbox" mapping="vou_id"  maxlength="32"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editlinkreqform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Event</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editlinkreqform-txt_crmevent_id" class="easyui-textbox" mapping="crmevent_id"  maxlength="32"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editlinkreqform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Code</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editlinkreqform-txt_code" class="easyui-textbox" mapping="code"  maxlength="32"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editlinkreqform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">SL part</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editlinkreqform-txt_slpart" class="easyui-textbox" mapping="slpart"  maxlength="32"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editlinkreqform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Data</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editlinkreqform-txt_data" class="easyui-textbox" mapping="data"  maxlength="2048"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editlinkreqform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Result</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editlinkreqform-txt_result" class="easyui-textbox" mapping="result"  maxlength="2048"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editlinkreqform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Status</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editlinkreqform-txt_status" class="easyui-textbox" mapping="status"  maxlength="3"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editlinkreqform_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Customer</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editlinkreqform-txt_custwa_id" class="easyui-textbox" mapping="custwa_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editlinkreqform_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editlinkreqform-txt_cust_id" class="easyui-textbox" mapping="cust_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editlinkreqform-autoadd" type="checkbox"><label for="pnl_editlinkreqform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editlinkreqform-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	


	<?php
	$custombuttonbar = __DIR__.'/cust-linkreqform-custombuttonbar.phtml';
	if (is_file($custombuttonbar)) {
		include $custombuttonbar;
	} else { ?>
	<div id="pnl_editlinkreqform-buttonbar" style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div id="pnl_editlinkreqform-buttonbar-left">
			<a id="pnl_editlinkreqform-btn_prev" class="easyui-linkbutton c8 fgta-button-detilprev" style="width: 50px">Prev</a>
			<a id="pnl_editlinkreqform-btn_next" class="easyui-linkbutton c8 fgta-button-detilnext" style="width: 50px">Next</a>
		</div>

		<div id="pnl_editlinkreqform-buttonbar-middle">
			<a id="pnl_editlinkreqform-btn_addnew" class="easyui-linkbutton c8 fgta-button-detiladd" style="width: 100px">Tambah Baru</a>
		</div>

		<div id="pnl_editlinkreqform-buttonbar-right">
			<a id="pnl_editlinkreqform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>
	<?php } ?>




</div>	
