<div id="pnl_editrateform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Currency Rate</div>
		<a id="pnl_editrateform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editrateform-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<form id="pnl_editrateform-form">

		<div class="form_row">
			<div class="form_label_col">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editrateform-txt_currrate_id" class="easyui-textbox" mapping="currrate_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editrateform-dt_currrate_date" class="easyui-datebox" style="width: 400px" mapping="currrate_date" data-options="editable:false ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Value</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editrateform-txt_currrate_value" class="easyui-numberbox" mapping="currrate_value" style="width: 400px" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editrateform-txt_curr_id" class="easyui-textbox" mapping="curr_id" uppercase="true" maxlength="10"  style="width: 400px" data-options="multiline:false  , disabled: true">
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editrateform-autoadd" type="checkbox"><label for="pnl_editrateform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editrateform-btn_save" class="easyui-linkbutton c1" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	



	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<a id="pnl_editrateform-btn_prev" class="easyui-linkbutton c8" style="width: 50px">Prev</a>
			<a id="pnl_editrateform-btn_next" class="easyui-linkbutton c8" style="width: 50px">Next</a>
		</div>

		<div>
			<a id="pnl_editrateform-btn_addnew" class="easyui-linkbutton c8" style="width: 100px">Tambah Baru</a>
		</div>

		<div>
			<a id="pnl_editrateform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>




</div>	
