<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Department Group</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row">
			<div class="form_label_col">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_deptgroup_id" class="easyui-textbox" mapping="deptgroup_id" uppercase="true" maxlength="10" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'ID Group harus diisi' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Dept Group</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_deptgroup_name" class="easyui-textbox" mapping="deptgroup_name" maxlength="60" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Nama Group harus diisi' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_deptgroup_isexselect" class="easyui-checkbox c1" mapping="deptgroup_isexselect" data-options="label: 'Exclude From Selection', labelWidth:'200px', labelPosition: 'after', disabled:false, checked: false ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_deptgroup_descr" class="easyui-textbox" mapping="deptgroup_descr"  maxlength="90" style="width: 400px" data-options="multiline: false  ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Parent</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_deptgroup_parent" class="easyui-combo" style="width: 400px" mapping="deptgroup_parent" display="deptgroup_parent_name" data-options="editable:false, valueField:'id', textField:'text' , prompt: 'NONE'">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">PathId</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_deptgroup_pathid" class="easyui-textbox" mapping="deptgroup_pathid"  maxlength="13" style="width: 400px" data-options="multiline: false , disabled: true ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Path</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_deptgroup_path" class="easyui-textbox" mapping="deptgroup_path"  maxlength="390" style="width: 400px" data-options="multiline: false , disabled: true ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Level</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_deptgroup_level" class="easyui-numberbox" mapping="deptgroup_level" style="width: 400px" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Type</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_depttype_id" class="easyui-combo" style="width: 400px" mapping="depttype_id" display="depttype_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Type Group harus diisi', prompt: '-- PILIH --'">
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	





	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="width">Hapus</a>
		</div>
	</div>

</div>

