<?php require_once dirname(__FILE__).'/itemmodel-list.phtml' ?>
<?php require_once dirname(__FILE__).'/itemmodel-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/itemmodel-propgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/itemmodel-propform.phtml' ?>



<?php
$customrecordstatus = __DIR__.'/itemmodel-customrecordstatus.phtml'; 
if (is_file($customrecordstatus)) {
	include $customrecordstatus;
} else { ?>

<?php } ?>
